apiVersion: v1
kind: Pod
metadata:
  name: cart-app-pod
  namespace: sudeep-ns
spec:
  containers:
    - name: test-containers
      image: sudeepsh/sre-test-image:1.0
      ports:
        - containerPort: 3015